# Generated by Django 4.2.20 on 2025-03-10 03:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('total_budget', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('cost_per_guest', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('cost_per_entertainment', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_guests', models.PositiveIntegerField()),
                ('max_entertainment_units', models.PositiveIntegerField()),
                ('objective', models.CharField(choices=[('MAX_GUESTS', 'Maximize Number of Guests'), ('MAX_ENTERTAINMENT', 'Maximize Entertainment Quality'), ('BALANCED', 'Balance Both Objectives')], default='BALANCED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OptimalSolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('optimal_guests', models.PositiveIntegerField()),
                ('optimal_entertainment_units', models.PositiveIntegerField()),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event_plan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='optimal_solution', to='events.eventplan')),
            ],
        ),
    ]
