# Generated by Django 4.2.20 on 2025-03-10 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventplan',
            name='min_entertainment_units',
            field=models.PositiveIntegerField(default=1, help_text='Minimum number of entertainment units required'),
        ),
    ]
