# Generated by Django 4.2.20 on 2025-03-10 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_eventplan_min_entertainment_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventplan',
            name='min_guests',
            field=models.PositiveIntegerField(default=1, help_text='Minimum number of guests required'),
        ),
    ]
