# Generated by Django 4.2.20 on 2025-03-10 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_eventplan_min_guests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventplan',
            name='max_entertainment_units',
        ),
        migrations.RemoveField(
            model_name='eventplan',
            name='max_guests',
        ),
    ]
